apiVersion: v1
kind: Service
metadata:
  name: mrservice
  labels:
    app: mr19
spec:
  # clusterIP: None
  ports:
    # - name: worker-port
    #   protocol: TCP
    #   port: 50051
    #   targetPort: 50051
    - port: 8000
      name: master-port
      protocol: TCP
      targetPort: http-server
    # - name: zk
    #   protocol: TCP
    #   port: 2181
    #   targetPort: 2181
  selector:
    app: mr19
    type: master
  # type: LoadBalancer # Kind doesn't support LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: mr19
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mr19
  template:
    metadata:
      labels:
        app: mr19
        type: worker
    spec:
      containers:
      - name: worker
        imagePullPolicy: IfNotPresent
        image: worker:latest
        ports:
        - containerPort: 50051
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
  labels:
    app: mr19
    type: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr19
  template:
    metadata:
      labels:
        app: mr19
    spec:
      containers:
      - name: master
        imagePullPolicy: IfNotPresent
        image: master:latest
        ports:
        - containerPort: 8000
          name: http-server
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP