# apiVersion: v1
# kind: Service
# metadata:
#   name: mrservice
#   labels:
#     app: mr19
# spec:
#   ports:
#     - name: wrkr
#       protocol: TCP
#       port: 50051 
#       targetPort: 50051
#     - name: mstr
#       protocol: TCP
#       port: 50052
#       targetPort: 50052
#     - name: zk
#       protocol: TCP
#       port: 2181
#       targetPort: 2181
#   selector:
#     app: mr19
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerdeployment
  labels:
    app: mr19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mr19
  template:
    metadata:
      labels:
        app: mr19
    spec:
      containers:
      - name: worker
        imagePullPolicy: IfNotPresent
        image: mr-worker:latest
        ports:
        - containerPort: 50051
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: masterdeployment
  labels:
    app: mr19
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mr19
  template:
    metadata:
      labels:
        app: mr19
    spec:
      containers:
      - name: master
        imagePullPolicy: IfNotPresent
        image: mrmaster:latest
        ports:
        - containerPort: 50052
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP